name: Pylint

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]  # Use a versão alvo do repo
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Se usar pyproject.toml/poetry, adapte aqui:
          # pip install . || pip install -e .
          pip install pylint

      - name: Run pylint (safe when no .py files)
        shell: bash
        run: |
          PYFILES="$(git ls-files '*.py')"
          if [ -z "$PYFILES" ]; then
            echo "No Python files to lint."; exit 0
          fi
          pylint $PYFILES
